# Generated by Django 3.2.16 on 2023-01-11 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Vouchers', 'Vouchers'), ('Bonuses', 'Bonuses'), ('Awards', 'Awards'), ('Sells', 'Sells'), ('Other', 'Other')], max_length=20, null=True)),
                ('note', models.TextField()),
                ('date_added', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.FloatField()),
                ('category', models.CharField(choices=[('Restaurants', 'Restaurants'), ('Gifts', 'Gifts'), ('Family', 'Family'), ('Phone Bill', 'Phone Bill'), ('Water Bill', 'Water Bill'), ('Electricity Bill', 'Electricity Bill'), ('Gas Bill', 'Gas Bill'), ('Television Bill', 'Television Bill'), ('Internet Bill', 'Internet Bill'), ('Transport costs', 'Transport costs'), ('Car Maintenance', 'Car Maintenance'), ('Shoes', 'Shoes'), ('Clothes', 'Clothes'), ('Sport', 'Sport'), ('Pharmacy', 'Pharmacy'), ('Doctor', 'Doctor'), ('Education', 'Education'), ('Books', 'Books'), ('Investments', 'Investments'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=20, null=True)),
                ('note', models.TextField()),
                ('date_added', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField()),
                ('category', models.CharField(choices=[('Restaurants', 'Restaurants'), ('Gifts', 'Gifts'), ('Family', 'Family'), ('Phone Bill', 'Phone Bill'), ('Water Bill', 'Water Bill'), ('Electricity Bill', 'Electricity Bill'), ('Gas Bill', 'Gas Bill'), ('Television Bill', 'Television Bill'), ('Internet Bill', 'Internet Bill'), ('Transport costs', 'Transport costs'), ('Car Maintenance', 'Car Maintenance'), ('Shoes', 'Shoes'), ('Clothes', 'Clothes'), ('Sport', 'Sport'), ('Pharmacy', 'Pharmacy'), ('Doctor', 'Doctor'), ('Education', 'Education'), ('Books', 'Books'), ('Investments', 'Investments'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=20, null=True)),
                ('date_added', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
