# Generated by Django 3.2.16 on 2022-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.FloatField()),
                ('category', models.CharField(choices=[('Restaurants', 'Restaurants'), ('Gifts', 'Gifts'), ('Family', 'Family'), ('Phone Bill', 'Phone Bill'), ('Water Bill', 'Water Bill'), ('Electricity Bill', 'Electricity Bill'), ('Gas Bill', 'Gas Bill'), ('Television Bill', 'Television Bill'), ('Internet Bill', 'Internet Bill'), ('Transport costs', 'Transport costs'), ('Car Maintenance', 'Car Maintenance'), ('Shoes', 'Shoes'), ('Clothes', 'Clothes'), ('Sport', 'Sport'), ('Pharmacy', 'Pharmacy'), ('Doctor', 'Doctor'), ('Education', 'Education'), ('Books', 'Books'), ('Investments', 'Investments'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=20, null=True)),
                ('note', models.TextField()),
                ('date_added', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Vouchers', 'Vouchers'), ('Bonuses', 'Bonuses'), ('Awards', 'Awards'), ('Sells', 'Sells'), ('Other', 'Other')], max_length=20, null=True)),
                ('note', models.TextField()),
                ('date_added', models.DateField()),
            ],
        ),
    ]
